### ISSUE TITLE
Quantity setting methods in ParticleClass should take list of strings 

### ISSUE THREAD

**Issue by nilssass** [Hendrik1704/particle-analysis#2]
The methods
- set_quantities_OSCAR2013(self,line_from_file)
- set_quantities_JETSCAPE(self,line_from_file)

should include the data type (int, float) when setting the members, so that a list of strings can also be passed. See set_quantities_OSCAR2013Extended(self,line_from_file)

**Comment by Hendrik1704** [comment]
Is implemented in all set functions.
