### ISSUE TITLE
Implement EventCharacteristics class

### ISSUE THREAD

**Issue by Hendrik1704** [Hendrik1704/particle-analysis#36]
This class is supposed to get a list of Particle objects for one event, e.g., from the Oscar class.
From the provided Particle objects in the list, it can compute $\varepsilon_n$ (on the level of particles).

A further enhancement would include also the computation of the energy/baryon/charge/strangeness densities on a lattice and a function to compute the eccentricities on the level of the densities.

@NGoetz I will start to implement a dummy of the class and its constructor in a new branch, where you can put the computation of the eccentricities on the particle level. For the density part, I need to implement a lattice class first. When it's pushed, I will write you a message.

**Comment by NGoetz** [comment]
This was achieved by #47
