### ISSUE TITLE
Choose uniform naming convention for file names

### ISSUE THREAD

**Issue by nilssass** [Hendrik1704/particle-analysis#40]
We should rename the python files containing the classes as they differ in their naming scheme. For example to import the Particle class the user needs to import
```python
from ParticleClass import Particle
```
while for Histogram it is
```python
from Histogram import Histogram
```
Remember to change this also in the documentation examples!

**Comment by Hendrik1704** [comment]
Merged all PR's, only the documentation has to be changed.
